# Generated by Django 2.1.2 on 2019-01-26 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SaleModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logofcons',
            name='payment_method',
            field=models.CharField(choices=[('1', '现金'), ('2', '微信'), ('3', '支付宝'), ('4', '银联卡'), ('5', '其他')], default=django.utils.timezone.now, max_length=200, verbose_name='支付方式'),
            preserve_default=False,
        ),
    ]
