# Generated by Django 2.1.2 on 2019-01-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='联系电话')),
                ('address', models.CharField(max_length=300, verbose_name='联系地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='员工姓名')),
                ('gender', models.CharField(choices=[('1', '女'), ('2', '男')], default='2', max_length=2, verbose_name='性别')),
                ('employee_ID', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='员工编号')),
                ('postion', models.CharField(max_length=20, verbose_name='职位名称')),
            ],
            options={
                'verbose_name': '职工信息表',
            },
        ),
        migrations.CreateModel(
            name='StoreName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=20, verbose_name='店铺名称')),
                ('department', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '门店信息表',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRmanagement.StoreName', to_field='department', verbose_name='所属店铺'),
        ),
    ]
